# Oppdater denne URL-en til riktig SOSI XMI-endepunkt
xmi_url: https://sosi.geonorge.no/svn/SOSI/SOSI Del 3/Statens kartverk/Havnedata_testing.xml

# Relativ bane for generert pygeoapi-konfigurasjon
output_filename: configs/havnedata-pygeoapi-config.yaml
